ALTER TABLE CAMPAIGN ADD COLUMN START_DATE_NEW VARCHAR(30);
UPDATE CAMPAIGN SET START_DATE_NEW = START_DATE;
ALTER TABLE CAMPAIGN DROP COLUMN START_DATE;
ALTER TABLE CAMPAIGN RENAME COLUMN START_DATE_NEW TO START_DATE;